name: story_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.2.0
  geocoding: ^3.0.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+2
  http: ^1.2.1
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  location: ^5.0.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
